### ISSUE TITLE
Tracks and Routes have faded/semi-transparent colors

### ISSUE THREAD

**Issue by ewaldgh** [JFritzle/Mapsforge-for-QMapShack#1]
First of all, many thanks for this great capability!
On my desktop system (Windows 10- 64bit) I installed an early version (July 2021) and since then routes/tracks show with faded colors, like there is some level of transparancy applied.  On my portable system I have installed the version 0.17.1 with QMS 1.16.1 and there are no issues.
De-installing QMS and reinstalling does not help, neither does running it without Mapsforge-for-QMS.
I updated to 0.17.1 on the desktop system, still same problem.   The .ini settings for both systems are identical as is the Java engine.
![image](https://user-images.githubusercontent.com/77490881/156553984-3ed1f527-356f-494c-8f31-d0d3ce16fab4.png).

When hovering over the track, it does show in bright red.  Changing map sources, colors, moving to colored slope style etc. everything works as supposed but shows in faded colors.    The track color in the picture is pink, which is very bright on my laptop and barely visible on my desktop system.

Before I open an issue at the QMS github repo, I wanted to check whether you may have an idea of what could have gone wrong.
Thanks in advance,
Ewald

**Comment by JFritzle** [comment]
Hi Ewald,

I guess value of transparency slider for tracks/routes/waypoints in upper right corner of QMS is the culprit.
Maybe in the past you shifted slider accidentally within your desktop installation, didn’t you?

Lower transparency = higher opacity:
![Low transparency](https://user-images.githubusercontent.com/62614244/156570593-1a2aad0f-8a1c-491a-9347-aea83f3ab7ae.png)

Higher transparency = lower opacity:
![High transparency](https://user-images.githubusercontent.com/62614244/156570675-3aa6af48-2d73-4834-88f6-2ec6a39cd55c.png)

Potentially registry branch `Computer\HKEY_CURRENT_USER\SOFTWARE\QLandkarte\QMapShack` survives de-installation of QMS and reinstalled QMS still uses saved transparency setting.

Kind regards
J.

**Comment by ewaldgh** [comment]
OMG, thanks so much!  I looked everywhere in the settings, but it was in front of me (albeit quite small) with the projects window.  All is again great now.   Thanks for your help!
