### ISSUE TITLE
Asking for some help on formats.

### ISSUE THREAD

**Issue by swork1** [JFritzle/Mapsforge-for-QMapShack#2]
I've been searching for mbtiles format of OAM for awhile now. OAM's website contains mbtiles maps but only up to zoom 11. I would like the better zoom  of 13-14 in mbtiles format.

Is there any easy way to find/create this format? Or somewhere I could search for it?

**Comment by JFritzle** [comment]
[Mobile Atlas Creator](https://mobac.sourceforge.io) (MOBAC) and [Mapsforge Tile Server](https://github.com/telemaxx/mapsforgesrv) potentially will do the job.
1.	Download and unzip [latest stable MOBAC version](https://sourceforge.net/projects/mobac/files/latest/download) into installation folder.
2.	Create Mapsforge Tile Server _Mapsforge_Tile_Server.xml_ as [custom XML source](https://mobac.sourceforge.io/wiki/index.php/Custom_XML_Map_Sources) in MOBAC installation’s subfolder _mapsources_ containing:
```
<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
   <name>Mapsforge Tile Server</name>
   <minZoom>0</minZoom>
   <maxZoom>18</maxZoom>
   <tileType>png</tileType>
   <url>http://127.0.0.1:60815/{$z}/{$x}/{$y}.png</url>
   <tileUpdate>None</tileUpdate>
   <backgroundColor>#000000</backgroundColor>
   <ignoreErrors>true</ignoreErrors>
   <serverParts></serverParts>
</customMapSource>
```
3.	Download and install Mapsforge Tile Server’s graphical user interface [Mapsforge-for-TMS-Clients](https://github.com/JFritzle/Mapsforge-for-TMS-Clients) and dependencies following installation instructions.
4.	Run Mapsforge-for-TMS-Clients and configure server’s TCP port to same value (e.g. `60815`) as in URL of custom XML source file _Mapsforge_Tile_Server.xml_.  
 Within GUI, select OAM map(s), Mapsforge theme, theme’s style and overlays, etc. to your choice and _Start_ Mapsforge Tile Server. Server will listen for client requests.
5.	Start Mobile Atlas Creator, create new _atlas_ and choose _MBTiles SQLite_ as desired atlas format.  
 Choose _Mapsforge Tile Server_ as MOBAC’s _Map Source_. MOBAC will send requests for tiles to running Mapsforge Tile Server.  
 Configure zoom levels etc. to be contained within MBTiles atlas, select area and finally _Create Atlas_.  
 Created atlas file _heidelberg.mbtiles_ has been successfully tested in OruxMaps.

![Mobac](https://user-images.githubusercontent.com/62614244/204085490-a555952e-ea47-4a3a-8bfa-9141eb0967bb.png)

**Comment by swork1** [comment]
This would work if I was wanting smaller amounts of the map. Sadly when I try to do an entire state (Alaska) I get hit with a limit error message.
![image](https://user-images.githubusercontent.com/43395644/204103043-32fdd43e-7e50-41cd-805c-ca7e93bfa6c9.png)

My goal is to get mbtiles for the entire United States

**Comment by JFritzle** [comment]
Proposal 1:
Please read [here ](https://mobac.sourceforge.io/forum/viewtopic.php?t=321) about the 500000 tiles limit. As MOBAC is open source, you could remove the 500000 tiles limit in source, recompile and create your own MOBAC jar file.

Proposal 2:
As you may read in the same article mentioned above, there is no tiles limit for pre-generated tiles from the file-system.   
1. Try one of my other tools: [Mapsforge-to-Tiles](https://github.com/JFritzle/Mapsforge-to-Tiles). This tool allows for specifying zoom level, min and max tile numbers in X and Y directions, generate requested tiles and stores them into one single folder on disk. Leave GUI's input field _Filename prefix_ empty. Rendered tiles are then named _zoom.tilex.tiley_.png.  
2. Split folder files into subfolders _zoom/tilex/tiley_ and rename files in subfolder _tiley_ to _tiley_.png.   
 Using _bash_ command language interpreter, this can be achieved by following one liner
`for file in *.png; do IFS=.; set $file; IFS=$'\n'; mkdir -p $1/$2 2>/dev/null; mv $file $1/$2/$3.png; done`
4. Create _Local_Tile_Files.xml_ as [custom XML source](https://mobac.sourceforge.io/wiki/index.php/Custom_XML_Map_Sources) in MOBAC installation’s subfolder _mapsources_ containing:
```
<localTileFiles>
   <name>Local Tile Files</name>
   <sourceType>DIR_ZOOM_X_Y</sourceType>
   <sourceFolder>path_of_toplevel_tiles_folder</sourceFolder>
   <backgroundColor>#000000</backgroundColor>
</localTileFiles>
```
5. Start Mobile Atlas Creator, create new _atlas_ and choose _MBTiles SQLite_ as desired atlas format.
Choose _Local Tile Files_ as MOBAC’s _Map Source_. MOBAC will now read tiles from disk folder _path_of_toplevel_tiles_folder_.
Configure zoom levels etc. to be contained within MBTiles atlas, select area and finally _Create Atlas_.

**Comment by swork1** [comment]
I tried both options. Option 2 was too slow and wouldn't work for my use case. Option 1 seems to work good as modifying the limit was very easy to do.

Thanks for all the help!
