### ISSUE TITLE
TCL doesn't detect Mapsforgesrv version number

### ISSUE THREAD

**Issue by Favez** [JFritzle/Mapsforge-for-QMapShack#3]
I had a working installation on Windows and all of a sudden I receive an error message when starting the TCL script: "Mapsforgesrv version is "unknonw", at least version 0.17.4 is required" (in german). I tried several mapsforgesrv versions both Java 8 and 11, the error remains the same.
Somehow the version string is not detected correctly.

**Comment by JFritzle** [comment]
Does "all of a sudden" mean that really nothing has been changed:
- no new Mapsforge-for-QMapShack.* files?
- no new mapsforgesrv JAR file?
- no new Java installation?

I have tried to improve Java and/or tile server error recognition. Please try updated Mapsforge-for-QMapShack.* files.

**Comment by Favez** [comment]
Yes! I literally didn't change a single file. Last week it worked, today not.
I'll try with the new files.

**Comment by Favez** [comment]
Ok! The new files did the trick. 

I had to set the whole path to java.exe in the Ini-File, otherwise I got an error message that the Java Version could not be detected.

**Comment by JFritzle** [comment]
Strange, the same phenomenon was just reported by another user. He also had the same problem with the Java call `java`, which was resolved by search path variable `PATH`. Maybe the result of a Windows update?

See discussions at [https://github.com/telemaxx/mapsforgesrv/issues/46](https://github.com/telemaxx/mapsforgesrv/issues/46) and at ["java -version" in cmd gives no result](https://stackoverflow.com/questions/65344301/java-versionin-cmd-gives-no-result). 

Luckily, setting the whole path to `java.exe` solved the problem and I can close the ticket.
