### ISSUE TITLE
java version can not be detected

### ISSUE THREAD

**Issue by mluckau** [JFritzle/Mapsforge-for-QMapShack#4]
![Screenshot_20231022_010652](https://github.com/JFritzle/Mapsforge-for-QMapShack/assets/6820488/ff9328e7-a486-4fce-85d4-6f88d04b39d2)

OS: Manjaro Linux

Java-Version:
![Screenshot_20231022_011000](https://github.com/JFritzle/Mapsforge-for-QMapShack/assets/6820488/dff92e14-caa4-4d41-ba45-c205fb727987)

**Comment by JFritzle** [comment]
Didn't recognize major Java version number when version number has omitted trailing zero elements, e.g. "21".
Updated tcl script should now accept Java version strings according to [JEP 223: New Version-String Scheme](https://openjdk.org/jeps/223)

**Comment by JFritzle** [comment]
Seems the problem was solved by the updated tcl script.
